#!/bin/python3

def show_title(ver):
    print("\033[1;31m _       __                __", end="")
    print("\033[1;96m                __            ")
    print("\033[1;31m| |     / /___  ____  ____/ /", end="")
    print("\033[1;96m___  ___  _____/ /_____  _____")
    print("\033[1;31m| | /| / / __ \/ __ \/ __  /", end="")
    print("\033[1;96m __ \/ _ \/ ___/ //_/ _ \/ ___/")
    print("\033[1;31m| |/ |/ / /_/ / /_/ / /_/ /", end="")
    print("\033[1;96m /_/ /  __/ /__/ ,< /  __/ /    ")
    print("\033[1;31m|__/|__/\____/\____/\__,_/", end="")
    print("\033[1;96m .___/\___/\___/_/|_|\___/_/     ")
    print("\033[1;96m                        /_/                           \033[0;0m")
    print("    Network Scanner          Version:", ver)
    print("-----------------------------------------------------------")
    print("Written by: Lothar TheQuiet")
    print("lotharthequiet@gmail.com")
    print("")
    print("")